import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";
// import Sidebar from "@/components/Sidebar";
import ResponsiveLayout from "@/components/ResponsiveLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* //flex flex-row justify-between`}> */}
        {/* <div className="w-32 bg-gray-200">
          test
        </div> */}
        <ResponsiveLayout>
        {/* <aside className="h-full flex md:block fixed w-50">
          <Sidebar />
        </aside> */}
          {children}
        </ResponsiveLayout>
        {/* <Sidebar></Sidebar> */}
      </body>
    </html>
  );
}
