import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
import Image from "next/image";
import SupabaseListener from '../auth/_components/supabase-listener'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  auth,
  children,
}: Readonly<{children: React.ReactNode, auth: React.ReactNode}>) {
  return (
    <div>
        <SupabaseListener />
        <div className="flex flex-col items-stretch bg-black">
          {auth}
          {children}
        </div>
    </div>
  );
}
